DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN
    CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS edge_devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS dataset_schemas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blob jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS model_cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  version text,
  is_private boolean NOT NULL DEFAULT false,
  is_gated boolean NOT NULL DEFAULT false,
  status approval_status NOT NULL DEFAULT 'pending',
  short_description text,
  full_description text,
  keywords text,
  author text,
  citation text,
  input_data text,
  input_type text,
  output_data text,
  foundational_model text,
  category text,
  documentation text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS publishers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  publisher_identifier text,
  publisher_identifier_scheme text,
  scheme_uri text,
  lang text
);

CREATE TABLE IF NOT EXISTS datasheets (
  identifier bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_year integer,
  resource_type text,
  resource_type_general text,
  size text,
  format text,
  version text,
  is_private boolean NOT NULL DEFAULT false,
  status approval_status NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  dataset_schema_id bigint REFERENCES dataset_schemas(id),
  publisher_id bigint REFERENCES publishers(id)
);

CREATE INDEX IF NOT EXISTS idx_datasheets_dataset_schema_id ON datasheets (dataset_schema_id);
CREATE INDEX IF NOT EXISTS idx_datasheets_status ON datasheets (status);
CREATE INDEX IF NOT EXISTS idx_datasheets_publisher_id ON datasheets (publisher_id);

CREATE TABLE IF NOT EXISTS datasheet_creators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  creator_name text NOT NULL,
  name_type text,
  lang text,
  given_name text,
  family_name text,
  name_identifier text,
  name_identifier_scheme text,
  name_id_scheme_uri text,
  affiliation text,
  affiliation_identifier text,
  affiliation_identifier_scheme text,
  affiliation_scheme_uri text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_creators_datasheet_id ON datasheet_creators (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_titles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  title text NOT NULL,
  title_type text,
  lang text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_titles_datasheet_id ON datasheet_titles (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_subjects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  subject text NOT NULL,
  subject_scheme text,
  scheme_uri text,
  value_uri text,
  classification_code text,
  lang text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_subjects_datasheet_id ON datasheet_subjects (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_contributors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  contributor_type text NOT NULL,
  contributor_name text NOT NULL,
  name_type text,
  given_name text,
  family_name text,
  name_identifier text,
  name_identifier_scheme text,
  name_id_scheme_uri text,
  affiliation text,
  affiliation_identifier text,
  affiliation_identifier_scheme text,
  affiliation_scheme_uri text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_contributors_datasheet_id ON datasheet_contributors (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_dates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  date text NOT NULL,
  date_type text NOT NULL,
  date_information text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_dates_datasheet_id ON datasheet_dates (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_alternate_identifiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  alternate_identifier text NOT NULL,
  alternate_identifier_type text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_datasheet_alt_ids_datasheet_id ON datasheet_alternate_identifiers (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_related_identifiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  related_identifier text NOT NULL,
  related_identifier_type text NOT NULL,
  relation_type text NOT NULL,
  related_metadata_scheme text,
  scheme_uri text,
  scheme_type text,
  resource_type_general text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_related_ids_datasheet_id ON datasheet_related_identifiers (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_rights (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  rights text,
  rights_uri text,
  rights_identifier text,
  rights_identifier_scheme text,
  scheme_uri text,
  lang text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_rights_datasheet_id ON datasheet_rights (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_descriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  description text NOT NULL,
  description_type text NOT NULL,
  lang text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_descriptions_datasheet_id ON datasheet_descriptions (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_geo_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  geo_location_place text,
  point_longitude numeric,
  point_latitude numeric,
  box_west numeric,
  box_east numeric,
  box_south numeric,
  box_north numeric,
  polygon jsonb
);
CREATE INDEX IF NOT EXISTS idx_datasheet_geo_locations_datasheet_id ON datasheet_geo_locations (datasheet_id);

CREATE TABLE IF NOT EXISTS datasheet_funding_references (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasheet_id bigint NOT NULL REFERENCES datasheets(identifier) ON DELETE CASCADE,
  funder_name text NOT NULL,
  funder_identifier text,
  funder_identifier_type text,
  scheme_uri text,
  award_number text,
  award_uri text,
  award_title text
);
CREATE INDEX IF NOT EXISTS idx_datasheet_funding_refs_datasheet_id ON datasheet_funding_references (datasheet_id);

CREATE TABLE IF NOT EXISTS models (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  version text,
  description text,
  owner text,
  location text,
  license text,
  framework text,
  model_type text,
  test_accuracy numeric(6,5),
  model_metrics jsonb,
  inference_labels jsonb,
  model_structure jsonb,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  model_card_id bigint NOT NULL UNIQUE REFERENCES model_cards(id)
);
CREATE INDEX IF NOT EXISTS idx_models_model_card_id ON models (model_card_id);

CREATE TABLE IF NOT EXISTS support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject text NOT NULL,
  category text NOT NULL DEFAULT 'General',
  priority text NOT NULL DEFAULT 'Medium',
  status text NOT NULL DEFAULT 'open',
  description text NOT NULL,
  submitted_by text NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT NOW(),
  admin_response text,
  reviewed_by text,
  reviewed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets (status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_submitted_by ON support_tickets (submitted_by);
CREATE INDEX IF NOT EXISTS idx_support_tickets_submitted_at ON support_tickets (submitted_at DESC);

CREATE TABLE IF NOT EXISTS submission_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  submitted_by text NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT NOW(),
  title text,
  data jsonb NOT NULL,
  asset_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  intake_method text,
  submission_origin text,
  admin_notes text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_asset_id bigint,
  created_asset_type text,
  error_message text,
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_submission_queue_status ON submission_queue (status);
CREATE INDEX IF NOT EXISTS idx_submission_queue_submitted_by ON submission_queue (submitted_by);
CREATE INDEX IF NOT EXISTS idx_submission_queue_submitted_at ON submission_queue (submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_submission_queue_type ON submission_queue (submission_type);

CREATE TABLE IF NOT EXISTS generated_dataset_artifacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artifact_key text NOT NULL UNIQUE,
  title text NOT NULL,
  source_dataset_id text NOT NULL,
  submitted_by text,
  planner_mode text NOT NULL DEFAULT 'deterministic',
  query_schema jsonb NOT NULL,
  generated_schema jsonb NOT NULL,
  derivation_plan jsonb NOT NULL,
  validation_report jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_csv_path text NOT NULL,
  output_schema_path text NOT NULL,
  status text NOT NULL DEFAULT 'generated',
  review_submission_id bigint REFERENCES submission_queue(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_generated_dataset_artifacts_source_dataset_id ON generated_dataset_artifacts (source_dataset_id);
CREATE INDEX IF NOT EXISTS idx_generated_dataset_artifacts_status ON generated_dataset_artifacts (status);

CREATE TABLE IF NOT EXISTS experiments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_at timestamptz NOT NULL,
  submitted_at timestamptz,
  executed_at timestamptz,
  model_used_at timestamptz,
  total_images integer,
  total_predictions integer,
  total_ground_truth_objects integer,
  true_positives integer,
  false_positives integer,
  false_negatives integer,
  precision numeric(6,5),
  recall numeric(6,5),
  f1_score numeric(6,5),
  mean_iou numeric(6,5),
  map_50 numeric(6,5),
  map_50_95 numeric(6,5),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  user_id bigint NOT NULL REFERENCES users(id),
  edge_device_id bigint NOT NULL REFERENCES edge_devices(id),
  model_id bigint NOT NULL REFERENCES models(id)
);
CREATE INDEX IF NOT EXISTS idx_experiments_user_id ON experiments (user_id);
CREATE INDEX IF NOT EXISTS idx_experiments_edge_device_id ON experiments (edge_device_id);
CREATE INDEX IF NOT EXISTS idx_experiments_model_id ON experiments (model_id);
CREATE INDEX IF NOT EXISTS idx_experiments_start_at ON experiments (start_at);

CREATE TABLE IF NOT EXISTS raw_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_name text NOT NULL,
  ground_truth jsonb,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS experiment_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experiment_id bigint NOT NULL REFERENCES experiments(id),
  raw_image_id bigint NOT NULL REFERENCES raw_images(id),
  image_count integer,
  image_received_at timestamptz,
  image_scored_at timestamptz,
  image_store_deleted_at timestamptz,
  image_decision text,
  top_label text,
  top_probability numeric(8,7),
  ingested_at timestamptz NOT NULL,
  scores jsonb,
  UNIQUE (experiment_id, raw_image_id)
);
CREATE INDEX IF NOT EXISTS idx_experiment_images_experiment_id ON experiment_images (experiment_id);
CREATE INDEX IF NOT EXISTS idx_experiment_images_raw_image_id ON experiment_images (raw_image_id);
CREATE INDEX IF NOT EXISTS idx_experiment_images_received_at ON experiment_images (image_received_at);
CREATE INDEX IF NOT EXISTS idx_experiment_images_ingested_at ON experiment_images (ingested_at);
