import asyncio
import json
from pathlib import Path as FilePath

import asyncpg
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from rest_server.agent_tool_models import (
    SubmitGeneratedArtifactRequest,
    SubmitGeneratedArtifactResponse,
    MissingColumnAnalysisRequest,
    MissingColumnAnalysisResponse,
    PaperSchemaSearchRequest,
    PaperSchemaSearchResponse,
    SchemaPoolItem,
    SynthesizeDatasetRequest,
    SynthesizeDatasetResponse,
)
from rest_server.database import get_pool
from rest_server.patra_agent_service import (
    AgentServiceError,
    _pair_map,
    _normalize_cache_dir,
    analyze_missing_columns_for_candidate,
    list_schema_pool,
    run_paper_schema_search,
)
from rest_server.patra_synthesis_service import (
    SynthesisServiceError,
    generate_synthesized_dataset,
)
from rest_server.routes.submissions import _insert_submission

router = APIRouter(prefix="/agent-tools", tags=["agent-tools"])


GENERATED_ARTIFACTS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS generated_dataset_artifacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artifact_key text NOT NULL UNIQUE,
  title text NOT NULL,
  source_dataset_id text NOT NULL,
  submitted_by text,
  planner_mode text NOT NULL DEFAULT 'deterministic',
  query_schema jsonb NOT NULL,
  generated_schema jsonb NOT NULL,
  derivation_plan jsonb NOT NULL,
  validation_report jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_csv_path text NOT NULL,
  output_schema_path text NOT NULL,
  status text NOT NULL DEFAULT 'generated',
  review_submission_id bigint REFERENCES submission_queue(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_generated_dataset_artifacts_source_dataset_id ON generated_dataset_artifacts (source_dataset_id);
CREATE INDEX IF NOT EXISTS idx_generated_dataset_artifacts_status ON generated_dataset_artifacts (status);
"""


async def _ensure_generated_artifacts_table(conn: asyncpg.Connection) -> None:
    await conn.execute(GENERATED_ARTIFACTS_TABLE_SQL)


async def _insert_generated_artifact(conn: asyncpg.Connection, payload: dict[str, object]) -> None:
    await _ensure_generated_artifacts_table(conn)
    await conn.execute(
        """
        INSERT INTO generated_dataset_artifacts (
            artifact_key, title, source_dataset_id, submitted_by, planner_mode,
            query_schema, generated_schema, derivation_plan, validation_report,
            metadata, output_csv_path, output_schema_path, status, updated_at
        )
        VALUES (
            $1, $2, $3, $4, $5,
            $6::jsonb, $7::jsonb, $8::jsonb, $9::jsonb,
            $10::jsonb, $11, $12, 'generated', NOW()
        )
        ON CONFLICT (artifact_key)
        DO UPDATE SET
            title = EXCLUDED.title,
            source_dataset_id = EXCLUDED.source_dataset_id,
            submitted_by = EXCLUDED.submitted_by,
            planner_mode = EXCLUDED.planner_mode,
            query_schema = EXCLUDED.query_schema,
            generated_schema = EXCLUDED.generated_schema,
            derivation_plan = EXCLUDED.derivation_plan,
            validation_report = EXCLUDED.validation_report,
            metadata = EXCLUDED.metadata,
            output_csv_path = EXCLUDED.output_csv_path,
            output_schema_path = EXCLUDED.output_schema_path,
            updated_at = NOW()
        """,
        payload["artifact_key"],
        payload["title"],
        payload["source_dataset_id"],
        payload["submitted_by"],
        payload["planner_mode"],
        json.dumps(payload["query_schema"]),
        json.dumps(payload["generated_schema"]),
        json.dumps(payload["derivation_plan"]),
        json.dumps(payload["validation_report"]),
        json.dumps(payload["metadata"]),
        payload["output_csv_path"],
        payload["output_schema_path"],
    )


async def _get_generated_artifact(conn: asyncpg.Connection, artifact_key: str):
    await _ensure_generated_artifacts_table(conn)
    row = await conn.fetchrow(
        """
        SELECT artifact_key, title, source_dataset_id, submitted_by, planner_mode,
               query_schema, generated_schema, derivation_plan, validation_report,
               metadata, output_csv_path, output_schema_path, status, review_submission_id
        FROM generated_dataset_artifacts
        WHERE artifact_key = $1
        """,
        artifact_key,
    )
    if not row:
        return None
    payload = dict(row)
    for key in ("query_schema", "generated_schema", "derivation_plan", "validation_report", "metadata"):
        if isinstance(payload.get(key), str):
            payload[key] = json.loads(payload[key])
    return payload


@router.get("/schema-pool", response_model=list[SchemaPoolItem])
async def get_schema_pool():
    try:
        return await asyncio.to_thread(list_schema_pool)
    except AgentServiceError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.post("/paper-schema-search", response_model=PaperSchemaSearchResponse)
async def paper_schema_search(payload: PaperSchemaSearchRequest):
    try:
        return await asyncio.to_thread(
            run_paper_schema_search,
            payload.document_path,
            payload.document_url,
            payload.document_text,
            payload.document_format,
            payload.top_k,
            payload.disable_llm,
            payload.api_base,
            payload.model,
            payload.api_key,
            payload.timeout_seconds,
            payload.cache_dir,
        )
    except AgentServiceError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.post("/missing-column-analysis", response_model=MissingColumnAnalysisResponse)
async def missing_column_analysis(payload: MissingColumnAnalysisRequest):
    try:
        return await asyncio.to_thread(
            analyze_missing_columns_for_candidate,
            payload.query_schema,
            payload.candidate_dataset_id,
            payload.cache_dir,
        )
    except AgentServiceError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.post("/generate-synthesized-dataset", response_model=SynthesizeDatasetResponse)
async def generate_synthesized_dataset_route(
    payload: SynthesizeDatasetRequest,
    pool: asyncpg.Pool = Depends(get_pool),
):
    try:
        result = await asyncio.to_thread(
            generate_synthesized_dataset,
            payload.query_schema,
            payload.candidate_dataset_id,
            payload.selected_fields,
            payload.use_llm_plan,
            payload.submitted_by,
            payload.api_base,
            payload.model,
            payload.api_key,
            payload.timeout_seconds,
            payload.cache_dir,
        )
    except (AgentServiceError, SynthesisServiceError) as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    storage = result.pop("storage")
    artifact = result["artifact"]
    async with pool.acquire() as conn:
        await _insert_generated_artifact(
            conn,
            {
                "artifact_key": artifact["artifact_key"],
                "title": artifact["title"],
                "source_dataset_id": artifact["source_dataset_id"],
                "submitted_by": payload.submitted_by,
                "planner_mode": artifact["planner_mode"],
                "query_schema": storage["query_schema"],
                "generated_schema": storage["generated_schema"],
                "derivation_plan": storage["derivation_plan"],
                "validation_report": storage["validation_report"],
                "metadata": storage["metadata"],
                "output_csv_path": storage["output_csv_path"],
                "output_schema_path": storage["output_schema_path"],
            },
        )
    return result


@router.get("/generated-artifacts/{artifact_key}")
async def get_generated_artifact(artifact_key: str, pool: asyncpg.Pool = Depends(get_pool)):
    async with pool.acquire() as conn:
        row = await _get_generated_artifact(conn, artifact_key)
    if not row:
        raise HTTPException(status_code=404, detail="Generated artifact not found")
    return {
        "artifact_key": row["artifact_key"],
        "title": row["title"],
        "source_dataset_id": row["source_dataset_id"],
        "submitted_by": row["submitted_by"],
        "planner_mode": row["planner_mode"],
        "status": row["status"],
        "review_submission_id": str(row["review_submission_id"]) if row["review_submission_id"] is not None else None,
        "metadata": row["metadata"],
        "output_csv_download_url": f"/agent-tools/generated-artifacts/{artifact_key}/download.csv",
        "output_schema_download_url": f"/agent-tools/generated-artifacts/{artifact_key}/download-schema",
    }


@router.get("/generated-artifacts/{artifact_key}/download.csv")
async def download_generated_csv(artifact_key: str, pool: asyncpg.Pool = Depends(get_pool)):
    async with pool.acquire() as conn:
        row = await _get_generated_artifact(conn, artifact_key)
    if not row:
        raise HTTPException(status_code=404, detail="Generated artifact not found")
    path = FilePath(row["output_csv_path"])
    if not path.exists():
        raise HTTPException(status_code=404, detail="Generated CSV file not found")
    return FileResponse(path, media_type="text/csv", filename=f"{artifact_key}.csv")


@router.get("/generated-artifacts/{artifact_key}/download-schema")
async def download_generated_schema(artifact_key: str, pool: asyncpg.Pool = Depends(get_pool)):
    async with pool.acquire() as conn:
        row = await _get_generated_artifact(conn, artifact_key)
    if not row:
        raise HTTPException(status_code=404, detail="Generated artifact not found")
    path = FilePath(row["output_schema_path"])
    if not path.exists():
        raise HTTPException(status_code=404, detail="Generated schema file not found")
    return FileResponse(path, media_type="application/json", filename=f"{artifact_key}-schema.json")


@router.post("/generated-artifacts/{artifact_key}/submit-review", response_model=SubmitGeneratedArtifactResponse)
async def submit_generated_artifact_for_review(
    artifact_key: str,
    payload: SubmitGeneratedArtifactRequest,
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        row = await _get_generated_artifact(conn, artifact_key)
        if not row:
            raise HTTPException(status_code=404, detail="Generated artifact not found")
        if row["review_submission_id"] is not None:
            return {
                "status": "ok",
                "message": "This generated artifact has already been submitted for admin review.",
                "artifact_key": artifact_key,
                "submission_id": str(row["review_submission_id"]),
            }

        normalized_cache = _normalize_cache_dir((row["metadata"] or {}).get("cache_dir"))
        pair_lookup = _pair_map(normalized_cache)
        source_pair = pair_lookup.get(row["source_dataset_id"])
        source_url = source_pair.source_url if source_pair else (row["metadata"] or {}).get("candidate_source_url", "")
        candidate_title = source_pair.title if source_pair else (row["metadata"] or {}).get("candidate_title", row["source_dataset_id"])
        title = payload.title or row["title"]
        description = (
            f"Synthesized PATRA dataset derived from {candidate_title}. "
            "This artifact was generated through a bounded PATRA workflow that only materializes direct or auditable deterministic derivations."
        )
        if payload.notes:
            description = f"{description}\n\nSubmitter notes: {payload.notes}"

        asset_payload = {
            "publication_year": None,
            "resource_type": "Dataset",
            "resource_type_general": "Dataset",
            "format": "text/csv",
            "version": "patra-synth-v1",
            "is_private": False,
            "dataset_schema_blob": row["generated_schema"],
            "publisher": {"name": "PATRA Generated Artifacts"},
            "titles": [{"title": title}],
            "creators": [{"creator_name": payload.submitted_by}],
            "subjects": [
                {"subject": "schema-search"},
                {"subject": "dataset-substitution"},
                {"subject": "synthetic-derivation"},
            ],
            "descriptions": [
                {"description": description, "description_type": "Abstract"},
                {
                    "description": "Pending PATRA admin review before admission into the shared datasheet pool.",
                    "description_type": "Other",
                },
            ],
            "related_identifiers": [
                {
                    "related_identifier": source_url or row["source_dataset_id"],
                    "related_identifier_type": "URL" if source_url else "Text",
                    "relation_type": "IsDerivedFrom",
                    "resource_type_general": "Dataset",
                },
                {
                    "related_identifier": f"/agent-tools/generated-artifacts/{artifact_key}/download.csv",
                    "related_identifier_type": "URL",
                    "relation_type": "HasPart",
                    "resource_type_general": "Dataset",
                },
            ],
        }
        submission_data = {
            "artifact_key": artifact_key,
            "title": row["title"],
            "source_dataset_id": row["source_dataset_id"],
            "planner_mode": row["planner_mode"],
            "metadata": row["metadata"],
            "validation_report": row["validation_report"],
            "notes": payload.notes or "",
        }
        submission = await _insert_submission(
            conn,
            "datasheet",
            payload.submitted_by,
            title,
            submission_data,
            asset_payload,
            "patra-agent-tools",
            "generated-dataset-artifact",
        )
        await conn.execute(
            """
            UPDATE generated_dataset_artifacts
            SET review_submission_id = $2,
                status = 'pending_review',
                updated_at = NOW()
            WHERE artifact_key = $1
            """,
            artifact_key,
            submission["id"],
        )

    return {
        "status": "ok",
        "message": "Generated artifact submitted to PATRA for admin review.",
        "artifact_key": artifact_key,
        "submission_id": str(submission["id"]),
    }
